### ISSUE TITLE
Writing of output data

### ISSUE THREAD

**Issue by olaszsoma** [osrep/NORSE_actor#5]
The results of the NORSE calculation have to be written to CPO structures. This has to be implemented to the code version. For this purpose, I will remove the continuation of the calculation currently implemented to the code, as the results can be written to CPOs after the first calculation, don't need to complicate the problem with a modification of the code parameters.
The data needed to be saved to CPO structures is the distribution of the electron population (`o.f` where `o` is the NORSE object). This is in xi and p coordinates. The convention of how to do it has been discussed in Bologna. The results obtained there should be followed for the implementation.

**Comment by olaszsoma** [comment]
The distribution probably should be transferred to Python variable from a Matlab variable, as the method for CPO writing is known in Python.

**Comment by olaszsoma** [comment]
The distribution is saved for a certain number of time steps determined by the variable `nSaveSteps`. In `o.f` the whole p-xi grid is saved `nSaveSteps` times. How this matrix is built up, I still have to figure out. For this, I will have a look into the 2D distribution plotting script, to see how does it plot the distribution (probably from `o.f`).

**Comment by olaszsoma** [comment]
Each column of the `o.f` matrix is the distribution function for a given time step in `BigVector` form. After a calculation, only the distribution for the last time step is needed. It will be seen if this is needed as a `BigVector` or in 2D matrix form.

**Comment by olaszsoma** [comment]
The variable can be read into Python now, but it is in Matlab double format. This will have to be changed to Python numpy array for CPO writing.

**Comment by gergopokol** [comment]
>  It will be seen if this is needed as a `BigVector` or in 2D matrix form.

Has it been decided, already? 1D might be easier to store, while 2D is easier to interpret...

**Comment by olaszsoma** [comment]
> > It will be seen if this is needed as a `BigVector` or in 2D matrix form.
> 
> Has it been decided, already? 1D might be easier to store, while 2D is easier to interpret...

For now, it is 1D. I don't see why it is harder to store it as 2D but will see. I am not sure which will be more convenient for CPO writing, that will decide it I think. The Python variable is a temporary storage of the data anyway.

**Comment by olaszsoma** [comment]
It seems that the output CPO can only be written if the time field is written as well. Otherwise, the output is not written. I have managed to write Equilibrium CPO this way, following an example Python file. I will modify it next to write something to the distribution CPO, which will be used for the final version of the actor.

**Comment by olaszsoma** [comment]
I have managed to write some data to the distribution CPO (time), but I had problem writing to the datainfo part. I am not sure that is necessary for us, but if so, it can be figured out how to write it. I will try to write the appropriate parts of the distribution CPO , and see if it works.

**Comment by olaszsoma** [comment]
The calculation results can now be written to the distribution CPO. The time and rho coordinates will have to be updated when the actor will be in a proper workflow. At the moment they are filled with one number only, but this can be easily rewritten according to the needs of a given simulation. This issue can be closed.
